blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Questions and Help
    url: https://github.com/react-hookz/web/discussions
    about: This is a bug tracker, not a support system. For usage questions, please use GitHub Discussions.
